version: '3'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
