services:
  - type: web
    name: backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"

  - type: web
    name: frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "80"
